# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "252191c59effa20ce15bfef0b4e02792"
name = "descriptoai"
handle = "descriptoai"
application_url = "https://searches-meetings-coming-vitamin.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://searches-meetings-coming-vitamin.trycloudflare.com/auth/callback", "https://searches-meetings-coming-vitamin.trycloudflare.com/auth/shopify/callback", "https://searches-meetings-coming-vitamin.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
